config/routes.rb
Citrus::Application.routes.draw do

  resources :splashes do
    resources :codes do
      member do
        get 'move'
      end
    end
  end

  resources :actions
  
  resources :codes do
    get :image
  end

  match 's/:shortcode' => 'codes#shortcode'
  root  :to => "pages#index"
  

end

app/models/splash.rb
class Splash
  include MongoMapper::Document
  include NestedAttributes
   
  key :name, String
  key :text, String
  key :photo, String
  
  validates_presence_of :name
  
  many :codes, :dependent => :destroy
  accepts_nested_attributes_for :codes, :allow_destroy => true
  validates_associated :codes
  
  many :actions, :polymorphic => true, :class_name => "Actions::Action"
  accepts_nested_attributes_for :actions, :allow_destroy => true
  validates_associated :actions
  
  validates_length_of :codes, :actions, :minimum => 1
  

  def self.available_actions
    [
     Actions::Twitter::FollowAction,
     Actions::Twitter::StatusUpdateAction,
     # Actions::Twitter::RetweetAction,
     Actions::Facebook::PublishStreamAction,
     Actions::Paypal::DonateAction,
     Actions::Platform::VisitLinkAction,
     Actions::Platform::CallAction,
     Actions::Foursquare::CheckInAction,
     Actions::Foursquare::SendFriendRequestAction,     
     Actions::Mailchimp::SubscribeAction
    ]
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  respond_to :json, :html

  def index
    @splashes = Splash.all

    respond_with(@splashes)
  end
  
  def show
    @splash = Splash.find_by_id(params[:id])
    respond_with(@splash)
  end
  
  def new
    @splash = Splash.new
    @splash.codes.build
    respond_with(@splash)
  end

  def edit
    @splash = Splash.find_by_id(params[:id])
  end
  
  def create
    @splash = Splash.new(params[:splash])
    flash[:notice] = 'Splash was successfully created.' if @splash.save
    respond_with(@splash)
  end
  
  def update
    @splash = Splash.find_by_id(params[:id])
    flash[:notice] = 'Splash was successfully updated.' if @splash.update_attributes(params[:splash])
    respond_with(@splash)
  end
  
  def destroy
    @splash = Splash.find_by_id(params[:id])
    flash[:notice] = 'Splash was successfully destroyed.' if @splash.destroy
    redirect_to splashes_path
  end
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/views/splashes/_form.html.haml
=  simple_form_for @splash, :html => {:class => "bp"} do |f|
  = f.input :id, :as => :hidden
  = f.input :name
  = f.input :text
  = f.input :photo

  %h3 Actions
  = f.error :actions unless f.object.actions.length > 0
  #actions_list
    = f.simple_fields_for :actions do |af|
      %div.action_box
        = render 'actions/form', :form => af

  .actions
    %a.add_new_action Add New Action    
    = select_tag 'new_action_type', options_for_select(@available_action_types)

  %h3 Codes
  = f.error :codes unless f.object.codes.length > 0 
  #codes_list.window
    = f.simple_fields_for :codes do |cf|
      = render 'codes/form', :form => cf
  
  .actions
    %a.add_new_code Add New Code
  
  .actions
    = f.button :submit

app/views/splashes/edit.html.haml
%h1 Editing Splash

= render 'form'

= link_to 'Show', @splash
\|
= link_to 'Back', splashes_path

app/views/splashes/index.html.haml
%h1 Listing splashes

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @splashes.each do |splash|
    %tr
      %td= splash.name
      %td= link_to 'Show', splash
      %td= link_to 'Edit', edit_splash_path(splash)
      %td= link_to 'Destroy', splash, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Splash', new_splash_path

app/views/splashes/new.html.haml
%h1 New Splash

= render 'form'

= link_to 'Back', splashes_path

app/views/splashes/show.html.haml
%p
  %b Name:
  = @splash.name
%p
  %b Text:
  = @splash.text

- if @splash.photo.present? && @splash.photo.length > 0
  %p
    %b Photo:
    = image_tag @splash.photo
%p
  %b 
    Actions:
  %ul
    - @splash.actions.each do |action|
      %li 
        = "#{action.action_text} - #{action.class.name.split("::")[1..-1].join().underscore.titleize}"

%p
  %b Codes leading to this splash
  %br
  - @splash.codes.each do |code|
    = image_tag code_image_path(code)

= link_to 'Edit', edit_splash_path(@splash)
\|
= link_to 'Back', splashes_path